# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
PassImg.create(img: 'glyphicon glyphicon-book')
PassImg.create(img: 'glyphicon glyphicon-bell')
PassImg.create(img: 'glyphicon glyphicon-tree-deciduous')
PassImg.create(img: 'glyphicon glyphicon-gift')
PassImg.create(img: 'glyphicon glyphicon-heart')
PassImg.create(img: 'glyphicon glyphicon-home')
PassImg.create(img: 'glyphicon glyphicon-apple')
PassImg.create(img: 'glyphicon glyphicon-lock')
PassImg.create(img: 'glyphicon glyphicon-asterisk')

Sentence.create(level: 1, sentence_frame: "The _____ is _____.")
Sentence.create(level: 1, sentence_frame: "The _____ has many _____.")
Sentence.create(level: 1, sentence_frame: "A _____ has a _____.")
Sentence.create(level: 1, sentence_frame: "I see _____.")
Sentence.create(level: 1, sentence_frame: "I like the _____.")
Sentence.create(level: 1, sentence_frame: "The _____ can _____.")
Sentence.create(level: 1, sentence_frame: "A _____ has lots of _____.")
Sentence.create(level: 1, sentence_frame: "The _____ has some _____.")
Sentence.create(level: 1, sentence_frame: "_____ can _____.")
Sentence.create(level: 1, sentence_frame: "_____ can see _____.")
Sentence.create(level: 1, sentence_frame: "_____ likes the _____.")
Sentence.create(level: 1, sentence_frame: "The _____ likes the _____.")
Sentence.create(level: 1, sentence_frame: "The _____ can see _____.")
Sentence.create(level: 1, sentence_frame: "The _____ will _____.")
Sentence.create(level: 1, sentence_frame: "_____ will _____.")
Sentence.create(level: 1, sentence_frame: "The _____ likes to _____.")
Sentence.create(level: 1, sentence_frame: " _____ is _____.")
Sentence.create(level: 1, sentence_frame: " _____ has many _____.")
Sentence.create(level: 1, sentence_frame: " _____ has a _____.")
Sentence.create(level: 1, sentence_frame: " A _____ can _____.")

Sentence.create(level: 2, sentence_frame: "The _____ likes to _____ in the _____.")
Sentence.create(level: 2, sentence_frame: "A _____ can _____ on the _____.")
Sentence.create(level: 2, sentence_frame: "A _____ can _____ in the _____.")
Sentence.create(level: 2, sentence_frame: "A _____ can _____ over the _____.")
Sentence.create(level: 2, sentence_frame: "A _____ can _____ under the _____.")
Sentence.create(level: 2, sentence_frame: "The _____ likes to _____ over the _____.")
Sentence.create(level: 2, sentence_frame: "The _____ liked to _____ in the _____.")
Sentence.create(level: 2, sentence_frame: "The _____ liked to _____ on the _____.")
Sentence.create(level: 2, sentence_frame: "_____ is in the _____.")
Sentence.create(level: 2, sentence_frame: "_____ was on the _____.")
Sentence.create(level: 2, sentence_frame: "_____ was under the _____.")
Sentence.create(level: 2, sentence_frame: "_____ is over the _____.")
Sentence.create(level: 2, sentence_frame: "The _____ is _____ in the _____.")
Sentence.create(level: 2, sentence_frame: "The _____ is _____ and _____.")
Sentence.create(level: 2, sentence_frame: "The _____ will _____ and _____.")
Sentence.create(level: 2, sentence_frame: "The _____ did _____ and _____.")
Sentence.create(level: 2, sentence_frame: "A _____ can _____ and _____.")
Sentence.create(level: 2, sentence_frame: "_____ will _____ and _____.")
Sentence.create(level: 2, sentence_frame: "_____ did _____ and _____.")
Sentence.create(level: 2, sentence_frame: "_____ was _____ in the _____.")

Sentence.create(level: 3, sentence_frame: "The _____ _____ is _____.")
Sentence.create(level: 3, sentence_frame: "A _____ _____ will sometimes _____.")
Sentence.create(level: 3, sentence_frame: "The _____ _____ went to _____.")
Sentence.create(level: 3, sentence_frame: "The _____ _____ went to _____.")
Sentence.create(level: 3, sentence_frame: "The _____ _____ jumped over the _____.")
Sentence.create(level: 3, sentence_frame: "The _____ _____ ran in the _____.")
Sentence.create(level: 3, sentence_frame: "A _____ quickly _____ in the _____.")
Sentence.create(level: 3, sentence_frame: "A _____ slowly _____ in the _____.")
Sentence.create(level: 3, sentence_frame: "A _____ loudly _____ in the _____.")
Sentence.create(level: 3, sentence_frame: "A _____ happily _____ in the _____.")
Sentence.create(level: 3, sentence_frame: "The _____ slowly _____ on the _____.")
Sentence.create(level: 3, sentence_frame: "The _____ quickly _____ on the _____.")
Sentence.create(level: 3, sentence_frame: "The _____ went to the _____ to _____.")
Sentence.create(level: 3, sentence_frame: "The _____ went on the _____ to _____.")
Sentence.create(level: 3, sentence_frame: "_____ was _____ to _____.")
Sentence.create(level: 3, sentence_frame: "The _____ likes to _____ because _____.")
Sentence.create(level: 3, sentence_frame: "_____ can _____ in the _____ because _____.")
Sentence.create(level: 3, sentence_frame: "_____ is in the _____ because _____.")
Sentence.create(level: 3, sentence_frame: "_____ was on the _____ because _____.")
Sentence.create(level: 3, sentence_frame: "The _____ can _____ because _____.")
